pipeline:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## DEV SLACK
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  slack-build-started:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    template: >
      *{{ build.author }}* started building `{{ lowercase build.branch }}` [{{ build.number}}] - {{ build.link }}

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## LINT
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  lint-api:
    group: lint
    image: node:latest
    commands:
    - cd api
    - npm i --silent
    - npm run lint
    # image: docker
    # commands:
    #   - docker build -t cavillo/dployer-api:latest -t cavillo/dployer-api:${DRONE_BUILD_NUMBER} -f .docker/api/Dockerfile .
    #   - docker run cavillo/dployer-api:${DRONE_BUILD_NUMBER} npm run lint
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  lint-client:
    group: lint
    group: lint
    image: node:latest
    commands:
    - echo $docker_username
    - echo $DOCKER_USERNAME
    - echo ${{docker_username}}
    - echo ${docker_username}
    - echo ${DOCKER_USERNAME}
    - echo ${{DOCKER_USERNAME}}
    - echo ${DOCKER_USERNAME}
    - echo ${DOCKER_ID}
    - cd client
    - npm i --silent
    - npm run lint
    # image: docker
    # commands:
    #   - docker build -t cavillo/dployer-client:latest -t cavillo/dployer-client:${DRONE_BUILD_NUMBER} -f .docker/client/Dockerfile .
    #   - docker run cavillo/dployer-client:${DRONE_BUILD_NUMBER} npm run lint
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## DOCKER
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  publish-api:
    group: publish
    image: plugins/docker
    settings:
      # context: .
      repo: cavillo/dployer-api
      dockerfile: .docker/api/Dockerfile
      tags:
        - ${DRONE_COMMIT_BRANCH}-latest
        - ${DRONE_COMMIT_BRANCH}-v${DRONE_BUILD_NUMBER}
    # when:
    #   event: push
    #   branch: master

  publish-client:
    group: publish
    image: plugins/docker
    settings:
      # context: .
      repo: cavillo/dployer-client
      dockerfile: .docker/client/Dockerfile
      tags:
        - ${DRONE_COMMIT_BRANCH}-latest
        - ${DRONE_COMMIT_BRANCH}-v${DRONE_BUILD_NUMBER}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    # when:
    #   event: push
    #   branch: master

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # DEV SLACK
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  slack-build-finished:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    when:
      status: [ success, failure ]
    template: >
      build `{{ lowercase build.branch }}` [{{ build.number}}] by *{{ build.author }}* finished [{{ uppercase build.status }}] - {{ build.link }}