pipeline:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## DEV SLACK
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  slack-build-started:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    template: >
      *{{ build.author }}* started building `{{ lowercase build.branch }}` [{{ build.number}}] - {{ build.link }}

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## LINT
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  lint-api:
    group: lint
    image: docker
    commands:
      - docker build -t cavillo/dployer-api:latest -t cavillo/dployer-api:${DRONE_BUILD_NUMBER} -f .docker/api/Dockerfile .
      - docker run cavillo/dployer-api:${DRONE_BUILD_NUMBER} npm run lint
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  lint-client:
    group: lint
    image: docker
    commands:
      - docker build -t cavillo/dployer-client:latest -t cavillo/dployer-client:${DRONE_BUILD_NUMBER} -f .docker/client/Dockerfile .
      - docker run cavillo/dployer-client:${DRONE_BUILD_NUMBER} npm run lint
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## LINT
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  publish-api:
    group: publish
    image: docker
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
      - docker build -t cavillo/dployer-api:latest -t cavillo/dployer-api:${DRONE_BUILD_NUMBER} -f .docker/api/Dockerfile .
      - docekr push cavillo/dployer-api:latest
      - docekr push cavillo/dployer-api:${DRONE_BUILD_NUMBER}
    secrets: [ docker_password, docker_id ]
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: master

  publish-client:
    group: publish
    image: docker
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
      - docker build -t cavillo/dployer-client:latest -t cavillo/dployer-client:${DRONE_BUILD_NUMBER} -f .docker/client/Dockerfile .
      - docekr push cavillo/dployer-client:latest
      - docekr push cavillo/dployer-client:${DRONE_BUILD_NUMBER}
    secrets: [ docker_password, docker_id ]
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: master

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # DEV SLACK
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  slack-build-finished:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    when:
      status: [ success, failure ]
    template: >
      build `{{ lowercase build.branch }}` [{{ build.number}}] by *{{ build.author }}* finished [{{ uppercase build.status }}] - {{ build.link }}