pipeline:
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## DEV SLACK
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  slack-build-started:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    template: >
      *{{ build.author }}* started building `{{ lowercase build.branch }}` [{{ build.number}}] - {{ build.link }}

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## LINT
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  lint-api:
    group: lint
    image: node:latest
    commands:
    - cd api
    - npm i --silent
    - npm run lint

  lint-client:
    group: lint
    group: lint
    image: node:latest
    commands:
    - cd client
    - npm i --silent
    - npm run lint

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  ## DOCKER
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # publish-api:
  #   group: publish
  #   image: plugins/docker
  #   settings:
  #     context: .
  #     repo: cavillo/dployer-api
  #     dockerfile: .docker/api/Dockerfile
  #     tags:
  #       - ${DRONE_COMMIT_BRANCH}-latest
  #       - ${DRONE_COMMIT_BRANCH}-v${DRONE_BUILD_NUMBER}
  #     secrets:
  #       - source: DOCKER_USERNAME
  #         target: username
  #       - source: DOCKER_PASSWORD
  #         target: password
    # when:
    #   event: push
    #   branch: master

  # publish-client:
  #   group: publish
  #   image: plugins/docker
  #   settings:
  #     context: .
  #     repo: cavillo/dployer-client
  #     dockerfile: .docker/client/Dockerfile
  #     tags:
  #       - ${DRONE_COMMIT_BRANCH}-latest
  #       - ${DRONE_COMMIT_BRANCH}-v${DRONE_BUILD_NUMBER}
  #     secrets:
  #       - source: DOCKER_USERNAME
  #         target: username
  #       - source: DOCKER_PASSWORD
  #         target: password
    # when:
    #   event: push
    #   branch: master

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # DEV SLACK
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  slack-build-finished:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    when:
      status: [ success, failure ]
    template: >
      build `{{ lowercase build.branch }}` [{{ build.number}}] by *{{ build.author }}* finished [{{ uppercase build.status }}] - {{ build.link }}