kind: pipeline
name: dployer-ci

steps:
  - name: slack-build-start
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: dployer
      template: >
          {{build.event}} to `{{ lowercase build.branch }}` by *{{ build.author }}* -> {{ build.link }}

  - name: lint-api
    group: lint
    image: node:latest
    commands:
    - cd api
    - npm i --silent
    - npm run lint
    when:
      event: [ pull_request ]
      branch: master

  - name: lint-client
    group: lint
    image: node:latest
    commands:
    - cd client
    - npm i --silent
    - npm run lint
    when:
      event: [ pull_request ]
      branch: master

  - name: dockerize-api
    image: plugins/docker
    settings:
      repo: cavillo/dployer-api
      target: dployer-api
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      tags:
        - latest
        - '${DRONE_BUILD_NUMBER}'
    when:
      event: push
      branch: master

  - name: dockerize-client
    image: plugins/docker
    settings:
      repo: cavillo/dployer-client
      target: dployer-client
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      tags:
        - latest
        - '${DRONE_BUILD_NUMBER}'
    when:
      event: push
      branch: master

  - name: dockerize-drone-plugin
    image: plugins/docker
    settings:
      repo: cavillo/dployer-drone-plugin
      target: dployer-drone-plugin
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      tags:
        - latest
        - '${DRONE_BUILD_NUMBER}'
    when:
      event: push
      branch: master

  - name: plugin-test
    image: cavillo/dployer-drone-plugin:latest
    settings:
      api_host: 'cavillo.co'
      api_port: 8002
      api_token: dployer_token
      application: test-app
      namespace: test
      deployment: hello-world
      image: hello-world

  - name: slack-build-finished
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: dployer
      template: >
        {{#success build.status}}
          {{build.event}} to `{{ lowercase build.branch }}` succeeded. Good job *{{ build.author }}*.
        {{else}}
          {{build.event}} to `{{ lowercase build.branch }}` failed. Please by *{{ build.author }}* fix me -> {{ build.link }}
        {{/success}}
    when:
      event: [ push, pull_request ]
      branch: master
