kind: pipeline
name: dployer-ci

steps:
  - name: lint-api
    group: lint
    image: node:latest
    commands:
    - cd api
    - npm i --silent
    - npm run lint
    when:
      event: [ pull_request ]
      branch: master

  - name: lint-client
    group: lint
    image: node:latest
    commands:
    - cd client
    - npm i --silent
    - npm run lint
    when:
      event: [ pull_request ]
      branch: master

  - name: dockerize-api
    image: plugins/docker
    settings:
      repo: cavillo/dployer-api
      target: dployer-api
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      tags:
        - latest
        - '${DRONE_BUILD_NUMBER}'
    # when:
    #   event: push
    #   branch: master

  - name: dockerize-client
    image: plugins/docker
    settings:
      repo: cavillo/dployer-client
      target: dployer-client
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      tags:
        - latest
        - '${DRONE_BUILD_NUMBER}'
    # when:
    #   event: push
    #   branch: master

  - name: slack-build-finished
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: dployer
      template: >
        {{#success build.status}}
          build {{build.number}} [{{ lowercase build.branch }}] succeeded. Good job *{{ build.author }}*.
        {{else}}
          build {{build.number}} [{{ lowercase build.branch }}] failed. Please by *{{ build.author }}* fix me {{ build.link }}
        {{/success}}
