pipeline:
  slack-build-started:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    template: >
      *{{ build.author }}* started building `{{ lowercase build.branch }}` [{{ build.number}}] - {{ build.link }}
    when:
      event: [ pull_request ]
      branch: master

  lint-api:
    group: lint
    image: node:latest
    commands:
    - cd api
    - npm i --silent
    - npm run lint
    when:
      event: [ pull_request ]
      branch: master

  lint-client:
    group: lint
    group: lint
    image: node:latest
    commands:
    - cd client
    - npm i --silent
    - npm run lint
    when:
      event: [ pull_request ]
      branch: master

  slack-build-finished:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: builds
    when:
      status: [ success, failure ]
      event: [ pull_request ]
      branch: master
    template: >
      build `{{ lowercase build.branch }}` [{{ build.number}}] by *{{ build.author }}* finished [{{ uppercase build.status }}] - {{ build.link }}
