kind: pipeline
name: dployer-ci

steps:
  - name: slack-build-started
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: dployer
      template: >
        *{{ build.author }}* started building `{{ lowercase build.branch }}` [{{ build.number}}] - {{ build.link }}

  - name: lint-api
    group: lint
    image: node:latest
    commands:
    - cd api
    - npm i --silent
    - npm run lint
    when:
      event: [ pull_request ]
      branch: master

  - name: lint-client
    group: lint
    image: node:latest
    commands:
    - cd client
    - npm i --silent
    - npm run lint
    when:
      event: [ pull_request ]
      branch: master

  - name: dockerize-api
    group: dockerize
    image: plugins/docker
    settings:
      repo: cavillo/dployer-api
      target: dployer-api
      debug: true
      secrets: [ docker_username, docker_password ]
      auto_tag: true
      # tags:
      # - '${DRONE_BUILD_NUMBER}'
    # when:
    #   event: push
      #   branch: master

  - name: dockerize-client
    group: dockerize
    image: plugins/docker
    settings:
      repo: cavillo/dployer-client
      target: dployer-client
      debug: true
      secrets: [ docker_username, docker_password ]
      auto_tag: true
      # tags:
      # - '${DRONE_BUILD_NUMBER}'
    # when:
    #   event: push
    #   branch: master

  - name: slack-build-finished
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: dployer
      template: >
        *{{ build.author }}* started building `{{ lowercase build.branch }}` [{{ build.number}}] - {{ build.link }}
