version: '2'
services:
  mongo:
    image: 'bitnami/mongodb:latest'
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGODB_USERNAME=usr_mongo_db
      - MONGODB_PASSWORD=pwd_mongo_db
      - MONGODB_DATABASE=dployer
  api:
    image: 'cavillo/dployer-api:latest'
    environment:
      - MONGO_AUTH_USER=usr_mongo_db
      - MONGO_AUTH_PASSWORD=pwd_mongo_db
    ports:
      - '8002:8002'
  client:
    image: 'cavillo/dployer-client:latest'
    environment:
      - DPLOYER_API_URL=http://localhost:8002
    ports:
      - '3000:3000'
