version: '2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin_usr
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    image: 'cavillo/dployer-api:latest'
    environment:
      - MONGO_AUTH_USER=mongo_admin_usr
      - MONGO_AUTH_PASSWORD=example
    ports:
      - '8002:8002'
  client:
    image: 'cavillo/dployer-client:latest'
    environment:
      - DPLOYER_API_URL=http://localhost:8002
    ports:
      - '3000:3000'
